// THIS FILE IS AUTOGENERATED
import { registerPage } from "./root"
import file0 from "!!raw-loader!./doc/index.md";
import file1 from "!!raw-loader!./doc/mechanics/servers.md";
import file2 from "!!raw-loader!./doc/migrations/v1.md";
import file3 from "!!raw-loader!./doc/migrations/v2.md";
import file4 from "!!raw-loader!./doc/notfound.md";
import file5 from "!!raw-loader!./doc/programming/learn.md";

export const registerPages = () => {
  registerPage("index.md", file0);
  registerPage("mechanics/servers.md", file1);
  registerPage("migrations/v1.md", file2);
  registerPage("migrations/v2.md", file3);
  registerPage("notfound.md", file4);
  registerPage("programming/learn.md", file5);
};
