export const TerminalHelpText: string[] = [
  "输入 'help name' 可查看某条命令的更多信息 ",
  " ",
  '    alias [-g] [name="value"]        创建或显示终端别名',
  "    analyze                          获取当前机器的信息 ",
  "    backdoor                         在当前机器上安装后门 ",
  "    buy [-l/-a/program]              通过暗网购买程序",
  "    cat [file]                       显示文件内容",
  "    cd [dir]                         切换到新目录",
  "    changelog                        显示更新日志",
  "    check [script] [args...]         将脚本的日志打印到终端",
  "    clear                            清除终端上的所有文本 ",
  "    cls                              同 'clear' 命令 ",
  "    connect [hostname]               连接到远程服务器",
  "    cp [src] [dest]                  复制文件",
  "    download [script/text file]      将脚本或文本文件下载到你的电脑",
  "    upload [dir]                     从你的电脑上传脚本或文本文件",
  "    expr [math expression]           计算数学表达式的值",
  "    free                             查看机器的内存（RAM）使用情况",
  "    grep [opts]... pattern [file]... 在每个 FILE 中搜索 PATTERN（字符串/正则表达式）并将结果打印到终端",
  "         [-O] [target file]",
  "    grow                             伪造服务器银行账户中的资金，增加可用金额。",
  "    hack                             入侵当前机器",
  "    help [command]                   显示本帮助文本，或某条命令的帮助信息",
  "    history [-c]                     显示终端历史记录",
  "    home                             连接到家用电脑",
  "    hostname                         显示机器的主机名",
  "    ipaddr                           显示机器的 IP 地址",
  "    kill [script/pid] [args...]      停止当前服务器上指定的脚本 ",
  "    killall                          停止当前机器上所有运行中的脚本",
  "    ls [dir] [-l] [-h] [-g pattern]  显示机器上的所有文件",
  "    lscpu                            显示机器的 CPU 核心数",
  "    mem [script] [-t n]              显示运行脚本所需的 RAM 大小",
  "    mv [src] [dest]                  移动/重命名文本或脚本文件",
  "    nano [files...]                  文本编辑器 - 打开并编辑一个或多个脚本或文本文件",
  "    ps                               显示当前正在运行的所有脚本",
  "    rm [OPTIONS]... [FILE]...        从服务器上删除文件",
  "    run [script] [-t n] [--tail]     运行程序、脚本或编程合约",
  "        [--ram-override n]",
  "        [--temporary] [args...]",
  "    scan                             打印所有可直接连接的网络连接",
  "    scan-analyze [d] [-a]            打印距离最多 d 个节点的所有服务器的信息",
  "    scp [files...] [server]          将脚本、文本文件或 .lit 文件复制到目标服务器",
  "    sudov                            显示你对这台电脑是否拥有 root 权限",
  "    tail [script/pid] [args...]      显示指定脚本的动态日志",
  "    top                              显示所有运行中的脚本及其 RAM 占用",
  "    unalias [alias name]             删除指定的别名",
  "    vim [files...]                   文本编辑器 - 以 vim 模式打开并编辑一个或多个脚本或文本文件",
  "    weaken                           降低当前机器的安全等级",
  "    wget [url] [target file]         从网络服务器获取代码/文本",
  " ",
];

const TemplatedHelpTexts: Record<string, (command: string) => string[]> = {
  scriptEditor: (command) => {
    return [
      `用法：${command} [file names...] | [glob]`,
      ` `,
      `在脚本编辑器中打开指定的文件。只有脚本（.js、.jsx、.ts、.tsx） `,
      `或文本文件（.txt、.json、.css）可以用脚本编辑器编辑。如果文件不存在，将会 `,
      `创建一个新文件。`,
      ` `,
      `如果只提供一个 glob 作为唯一参数，${command} 可以遍历目录并一次性打开所有匹配的 `,
      `文件。${command} 无法通过 glob 创建文件，因此你的脚本必须已经存在。`,
      ` `,
      `示例：`,
      ` `,
      `    ${command} test.js`,
      `    ${command} test.js test2.js`,
      ` `,
      `    ${command} test.*`,
      `    ${command} /my-dir/*.js`,
      ` `,
    ];
  },
};

export const HelpTexts: Record<string, string[]> = {
  alias: [
    '用法：alias [-g] [name="value"] ',
    " ",
    "创建或显示别名。别名可以将一个词替换为另一个字符串。 ",
    "它可用于缩写常用的命令，或命令中常用的部分。别名的 NAME ",
    "定义了要被替换的词，而 VALUE 定义了替换后的内容。例如，",
    "你可以使用以下命令为终端命令 'run NUKE.exe' 创建名为 'nuke' 的别名： ",
    " ",
    '    alias nuke="run NUKE.exe"',
    " ",
    "之后，要运行 NUKE.exe 程序，你只需在终端中输入 'nuke'，而不必输入完整命令。 ",
    "请注意，'default'（默认）别名只会被替换终端命令的第一个词。 ",
    "例如，如果设置了以下别名： ",
    " ",
    '    alias worm="HTTPWorm.exe"',
    " ",
    "然后你尝试运行以下终端命令： ",
    " ",
    "    run worm",
    " ",
    "这会失败，因为 worm 别名并不是终端命令的第一个词。若要让别名可以在终端命令的 ",
    "任意位置被替换（而不只是第一个词），必须使用 -g 标志将其设置为全局别名： ",
    " ",
    '    alias -g worm="HTTPWorm.exe"',
    " ",
    "现在，只要 'worm' 作为独立的单词出现在终端命令中的任何位置，它都会被替换。 ",
    " ",
    "仅输入不带任何参数的 'alias' 命令，会以可复用的形式 ",
    "'alias NAME=VALUE' 在终端上打印所有已定义别名的列表。 ",
    " ",
    "可以使用 'unalias' 命令来移除别名。",
    "注意：  --all 别名保留用于移除操作。",
    " ",
  ],
  analyze: [
    "用法：analyze",
    " ",
    "打印当前服务器的详细信息与统计数据。打印的信息包括基本 ",
    "服务器详情，如主机名、玩家是否拥有 root 权限、哪些端口开启/关闭，还包括 ",
    "与黑客相关的信息，如成功入侵的预估几率、服务器上可用资金的 ",
    "预估值等。",
    " ",
  ],
  backdoor: [
    "用法：backdoor",
    " ",
    "在当前服务器上安装后门，使玩家可以从任意 ",
    "服务器连接到它。根据服务器的不同，还可能给予秘密奖励，例如商店折扣。",
    " ",
    "需要 root 权限才能运行。",
    " ",
  ],
  buy: [
    "用法：buy [-l / -a / program]",
    " ",
    "通过暗网购买程序。需要 TOR 路由器才能使用。",
    " ",
    "如果使用 '-l' 标志运行此命令，会在终端中显示所有可通过暗网购买的程序， ",
    "以及它们的价格。",
    " ",
    "如果使用 '-a' 标志运行此命令，将尝试购买所有未拥有的程序。",
    " ",
    "否则，必须将程序名作为参数传入。此名称不区分大小写。",
    " ",
  ],
  cat: [
    "用法：cat [file name]",
    " ",
    "显示消息（.msg）、文学（.lit）、脚本（.js、.jsx、.ts、.tsx）或文本（.txt、.json、.css）文件。示例：",
    " ",
    "    cat j1.msg",
    " ",
    "    cat foo.lit",
    " ",
    "    cat servers.txt",
    " ",
  ],
  cd: [
    "用法：cd [dir]",
    " ",
    "切换到指定的目录。不能切换到不存在的目录。示例：",
    " ",
    "    cd scripts/hacking",
    " ",
    "    cd /logs",
    " ",
    "    cd ../",
    " ",
  ],
  changelog: ["用法：changelog", " ", "显示更新日志。", " "],
  check: [
    "用法：check [script name] [args...]",
    " ",
    "将脚本名和参数所指定脚本的日志打印到终端。每个参数之间必须用空格分隔。 ",
    "请记住，运行中的脚本由其名称和启动时使用的参数唯一标识。 ",
    "因此，如果脚本是以以下参数启动的： ",
    " ",
    "    run foo.js 1 2 foodnstuff",
    " ",
    "那么要对这个脚本执行 'check' 命令，你必须传入相同的参数： ",
    " ",
    "    check foo.js 1 2 foodnstuff",
    " ",
  ],
  clear: [
    "用法：clear",
    " ",
    "清空终端屏幕，删除所有文本。注意这不会删除用户的命令历史，因此使用上下 ",
    "方向键仍然有效。另请注意此操作是永久性的，无法撤销。与 'cls' 命令同义",
    " ",
  ],
  cls: [
    "用法：cls",
    " ",
    "清空终端屏幕，删除所有文本。注意这不会删除用户的命令历史，因此使用上下 ",
    "方向键仍然有效。另请注意此操作是永久性的，无法撤销。与 'clear' 命令同义",
    " ",
  ],
  connect: [
    "用法：connect [hostname]",
    " ",
    "连接到远程服务器。必须将远程服务器的主机名作为此命令的参数 ",
    "传入。注意只能连接到网络中与当前服务器直接相邻的服务器，以及已安装",
    "后门的服务器。要查看可以连接哪些服务器，请使用 'scan' 命令。",
    " ",
  ],
  cp: ["用法：cp [src] [dest]", " ", "在此服务器上复制文件。要将文件复制到其他服务器请使用 scp。", " "],
  download: [
    "用法：download [script/text file]",
    " ",
    "将脚本或文本文件下载到你的电脑（比如现实中你的电脑）。",
    " ",
    "你也可以使用以下终端命令将所有脚本/文本文件打包为一个 zip 文件下载：",
    " ",
    "下载所有脚本和文本文件：download *",
    " ",
    "下载所有 JS 脚本：download *.js",
    " ",
    "下载所有文本文件：download *.txt",
    " ",
  ],
  upload: [
    "用法：upload [dir]",
    " ",
    "将你电脑上的一个目录上传到游戏中。",
    " ",
    "示例：",
    " ",
    "    upload path/to/dir",
    " ",
    "    upload .",
    " ",
  ],
  expr: [
    "用法：expr [mathematical expression]",
    " ",
    "计算简单的数学表达式。支持 JavaScript 原生运算符：",
    " ",
    "+, -, /, *, **, %",
    " ",
    "示例：",
    " ",
    "    expr 25*2",
    `    expr "25 * 2 ** 10"`,
    " ",
    `除了小数点（"."）、圆括号（"(" 和 ")"）以及字母 "e" 和 "E"（用于科学计数法）之外， `,
    `大多数非数字字符都不允许出现，并将从输入中被移除。`,
    "某些特殊情况可能需要用引号括起来才能正确计算。",
    " ",
  ],
  free: [
    "用法：free",
    " ",
    "显示当前机器的内存使用情况。打印当前服务器上可用的 RAM 总量，以及 ",
    "其中已被使用的部分。",
    " ",
  ],
  grep: [
    "用法：grep [OPTION]... PATTERN [FILE]... [-O] [OUTFILE] [-B/A/C] [NUM]",
    " ",
    "在每个 FILE 中搜索 PATTERN 并将结果打印到终端。",
    "示例：grep -n -h 'hello world' file1.js file2.txt -O output.txt -C 10 -V",
    " ",
    "选项（OPTIONS）： ",
    "  --help                   输出此用法信息并退出",
    " ",
    "搜索控制：",
    "  -* --search-all          在服务器上的每个 FILE 中搜索 PATTERN。忽略传入的任何 FILE 参数",
    "  -p --pipe-terminal       在终端输出中搜索 PATTERN。忽略传入的任何 FILE 参数",
    " ",
    "模式选择与解释：",
    "  -R, --regexp       PATTERN 为基本正则表达式。默认情况下 PATTERN 是字符串",
    " ",
    "输出控制：",
    "  -m --max-count NUM       选出 NUM 行后停止",
    "  -H --with-filename       在输出行中打印文件名。传入多个 FILE 参数时默认启用",
    "  -h --no-filename         不在输出行中打印文件名。传入单个 FILE 参数时默认启用。会覆盖 -H",
    "  -n --line-number         在输出行中打印行号",
    "  -q --quiet --silent      不向终端打印",
    "  -O --output OUTFILE      将输出写入文本文件。其后的参数必须是有效的文本文件（.txt、.json、.css）。默认不会覆盖已有文件",
    "  -f --allow-overwrite     与 [-O/--output] 组合使用，以允许覆盖指定的输出文件",
    " ",
    "上下文控制：",
    "  -B --before-context NUM  打印 NUM 行前导上下文",
    "  -A --after-context NUM   打印 NUM 行后置上下文",
    "  -C --context NUM         打印 NUM 行输出上下文",
    " ",
    "杂项：",
    "  -V --verbose             在常规输出之后打印 PATTERN、匹配数及搜索过的 FILE",
    "  -v --invert-match        选择不匹配的行",
    " ",
    "多个常规 OPTION 可以合并成一个。上下文、max-count 和输出 OPTION 必须分开写。示例：grep test -VnH* -O output.txt -C 5",
    "默认情况下 PATTERN 被解释为简单字符串。",
    "必须传入至少一个 FILE 参数，或者传入 -*/--search-all 来搜索所有文件。",
    "-m、-O 和 -B/A/C 之后紧跟的参数会被解释为该 OPTION 的参数。",
    '如果遇到参数解析困难，请考虑显式地将字符串作为 PATTERN 传入。示例：grep -G "(complex|regexp|\\w+)" script.js',
    " ",
  ],
  grow: [
    "用法：grow",
    " ",
    "伪造当前服务器上的交易，增加入侵可获得的资金。需要 root 权限。",
    "更多信息请前往 文档 > 资源 > NS API 文档 > Grow。",
    " ",
  ],
  hack: [
    "用法：hack",
    " ",
    "更多信息请前往 文档 > 资源 > NS API 文档 > Hack。",
    " ",
  ],
  help: [
    "用法：help [command]",
    " ",
    "显示终端帮助信息。不带参数时，'help' 会打印所有有效终端命令的列表及其功能的简要 ",
    "说明。你也可以将终端命令名作为参数传给 'help'，以打印有关该终端命令 ",
    "更详细的信息。示例： ",
    " ",
    "    help alias",
    " ",
    "    help scan-analyze",
    " ",
  ],
  history: [
    "用法：history [-c]",
    " ",
    "不带参数时，显示终端命令历史。要清除历史，请传入 '-c' 参数。",
    " ",
  ],
  home: [
    "用法：home",
    " ",
    "连接到你的家用电脑。无论你当前连接的是哪个服务器都可以使用。",
    " ",
  ],
  hostname: ["用法：hostname", " ", "打印当前服务器的主机名", " "],
  ipaddr: ["用法：ipaddr", " ", "打印当前服务器的 IP 地址", " "],
  kill: [
    "用法：kill [script name] [args...] 或 kill [pid]",
    " ",
    "通过脚本名和参数，或通过 PID 来终止指定的脚本。",
    " ",
    "如果你使用文件名和参数来终止脚本，则每个 ",
    "参数必须用空格分隔。请记住，运行中的脚本由 ",
    "其名称和启动时使用的参数唯一标识。因此，如果脚本 ",
    "是以以下参数启动的：",
    " ",
    "    run foo.js 1 sigma-cosmetics",
    " ",
    "那么要终止这个脚本，必须使用相同的参数：",
    " ",
    "    kill foo.js 1 sigma-cosmetics",
    " ",
    "如果你使用 PID 来终止脚本，则 PID 参数必须是数字",
    " ",
  ],
  killall: ["用法：killall", " ", "终止当前服务器上的所有脚本。"],
  ls: [
    "用法：ls [dir] [-l] [-h] [-g, --grep pattern]",
    " ",
    "不带参数的 ls 命令会将当前服务器目录下的所有文件和目录打印到终端屏幕上。 ",
    "文件将按字母顺序显示。 ",
    " ",
    "'dir' 可选参数可用于显示另一个目录中的文件/目录。",
    " ",
    "'-l' 可选参数可以让每一项独占一行，并显示两列：脚本的 RAM 占用和文件大小。",
    " ",
    "'-h' 可选参数可以将 '-l' 显示的文件大小以人类可读的格式（如 KB、MB、GB）显示，而不是字节数。",
    " ",
    "'--grep pattern' 可选参数可用于只显示文件名匹配指定模式的文件。",
    " ",
    "示例：",
    " ",
    "列出当前目录下扩展名为 '.js' 的所有文件：",
    " ",
    "    ls -l --grep .js",
    " ",
    "列出根目录下扩展名为 '.js' 的所有文件：",
    " ",
    "    ls / -l --grep .js",
    " ",
    "列出 'scripts' 目录下文件名中含有 'purchase' 一词的所有文件：",
    " ",
    "    ls scripts -l --grep purchase",
    " ",
  ],
  lscpu: ["用法：lscpu", " ", "打印当前服务器的 CPU 核心数", " "],

  mem: [
    "用法：mem [script name] [-t num_threads]",
    " ",
    "显示以单线程运行指定脚本所需的 RAM 大小。此命令也可以配合 '-t' 标志打印 ",
    "以多线程运行脚本所需的 RAM 大小。如果指定了 '-t' 标志，则必须在后面 ",
    "传入线程数参数。示例：",
    " ",
    "    mem foo.js",
    " ",
    "    mem foo.js -t 50",
    " ",
    "上面的第一个示例会打印单线程运行 'foo.js' 所需的 RAM 大小。第二个示例 ",
    "会打印 50 线程运行 'foo.js' 所需的 RAM 大小。",
    " ",
  ],
  mv: [
    "用法：mv [src] [dest]",
    " ",
    "将源文件移动到指定的目标位置。也可用于重命名文件。 ",
    "此命令只适用于脚本（.js、.jsx、.ts、.tsx）和文本文件（.txt、.json、.css）。此命令不能用于 ",
    "转换为其他文件类型",
    " ",
    "注意，与 Linux 的 'mv' 命令不同，目标参数必须是 ",
    "完整的文件路径。 ",
    "示例： ",
    " ",
    "    mv hacking-controller.js scripts/hacking-controller.js",
    " ",
    "    mv myScript.js myOldScript.js",
    " ",
  ],
  nano: TemplatedHelpTexts.scriptEditor("nano"),
  ps: [
    "用法：ps [OPTION]...",
    " ",
    "打印服务器上当前运行的脚本信息。",
    " ",
    "-g, --grep <pattern> 使用搜索模式按文件名筛选运行中的脚本。",
    " ",
    "如果不提供任何选项，ps 会列出所有运行中的脚本。",
    " ",
    "示例：",
    "  ps",
    "  ps --grep early-hack-template.js",
    "  ps -g n00dles.js",
  ],
  rm: [
    "用法：rm [OPTION]... [FILE]...",
    " ",
    "删除指定的文件（FILE）。",
    " ",
    "-f, --force					强制删除多个文件。",
    "-r, -R, --recursive	递归删除目录及其内容。",
    "--no-preserve-root		不特殊处理 '/'。",
    " ",
    "默认情况下，rm 不会对目录进行操作。要删除整个目录，请使用 --recursive（-r 或 -R）选项。",
    " ",
    "要删除名称以 '-' 开头的文件，例如 '-foo.js'，请使用以下命令之一：",
    "rm -- -foo.js",
    "rm ./-foo.js",
    " ",
    "注意，如果使用 rm 删除文件，文件的内容将会丢失。此操作不可逆。",
  ],
  run: [
    "用法：run [file name] [-t num_threads] [--tail] [--ram-override ram_in_GBs] [--temporary] [args...]",
    " ",
    "运行程序、脚本或编程合约。",
    " ",
    "'[-t num_threads]'、'[--tail]'、`[--ram-override ram_in_GBs]`、[--temporary] 和 '[args...]' 参数仅在",
    "运行脚本时有效。'-t' 标志用于指示脚本应以指定的线程数运行。",
    "如果省略该标志，脚本默认以单线程运行。",
    "'--tail' 标志用于立即为正在运行的脚本打开日志窗口。'--ram-override' 标志用于",
    "覆盖脚本运行时的 RAM 大小（每线程）。如果脚本最终使用的 RAM 超过该值，",
    "它将会崩溃。'--temporary' 标志用于指示该脚本不应包含在存档数据中。你必须在 'run' 之后、任何标志之前指定 [file name]。你可以按任意顺序使用内置标志，或将它们",
    "与自定义标志混合使用。",
    " ",
    "注意：'ns.args' 只包含自定义标志，不包含内置标志。如果想显式地将这些内置标志传给脚本，可以使用 '--' 结束特殊参数的处理。例如：",
    "- 'run a.js -t 5'：以 5 线程运行 a.js。'ns.args' 是一个空数组。",
    "- 'run a.js -- -t 10'：以 1 线程运行 a.js。'ns.args' 是数组：['-t', 10]。",
    " ",
    "[args...] 表示将传入脚本的任意数量的参数。参见关于脚本参数的文档。 ",
    "每个指定的参数必须用空格分隔。 ",
    " ",
  ],
  scan: [
    "用法：scan",
    " ",
    "打印所有可直接连接的网络连接。这将列出你当前可以使用 'connect' 终端命令连接到的 ",
    "所有服务器。",
    " ",
  ],
  "scan-analyze": [
    "用法：scan-analyze [depth] [-a]",
    " ",
    "打印网络上距离最多 [depth] 个节点的所有服务器的详细信息。调用 ",
    "'scan-analyze 1' 将显示与 'scan' 终端 ",
    "命令所示相同的服务器信息。此命令还会显示到达每个服务器的相对路径。",
    " ",
    "默认情况下，'scan-analyze' 可指定的最大深度为 3。不过，一旦你拥有 ",
    "DeepscanV1.exe 和 DeepscanV2.exe 程序，就可以分别以最大 ",
    "5 和 10 的深度执行 'scan-analyze'。",
    " ",
    "'scan-analyze' 显示的每个服务器信息包括你是否拥有它的 root 权限、 ",
    "所需的黑客等级、在其上运行 NUKE.exe 所需的开放端口数，以及它的 ",
    "RAM 大小。",
    " ",
    "默认情况下，此命令不会显示你购买的服务器。不过，如果希望启用该功能，你可以在 ",
    "命令末尾传入 -a 标志。",
    " ",
  ],
  scp: [
    "用法：scp [file names...] [target server]",
    " ",
    "将指定的文件从当前服务器复制到目标服务器。 ",
    "此命令只适用于脚本文件（.js、.jsx、.ts、.tsx）、文本文件（.txt、.json、.css） ",
    "和文学文件（.lit）。",
    "传入的第二个参数必须是目标服务器的主机名或 IP。示例：",
    " ",
    "    scp foo.js n00dles",
    " ",
    "    scp foo.js bar.js n00dles",
    " ",
  ],
  sudov: ["用法：sudov", " ", "打印你对当前机器是否拥有 root 权限", " "],

  tail: [
    "用法：tail [script name] [args...]",
    " ",
    "显示由脚本名和参数所指定脚本的动态日志。每个参数必须用空格分隔 ",
    "请记住，运行中的脚本由其名称和启动时使用的参数唯一标识 ",
    "因此，如果脚本是以以下参数启动的： ",
    " ",
    "    run foo.js 10 50000",
    " ",
    "那么要用 'tail' 查看其日志，必须使用相同的参数： ",
    " ",
    "    tail foo.js 10 50000",
    " ",
  ],
  top: [
    "用法：top",
    " ",
    "打印当前服务器上所有运行中的脚本列表，以及它们的线程数和总共占用的 ",
    "RAM 大小。",
    " ",
  ],
  unalias: [
    "用法：unalias [alias name]",
    "用法：unalias -all",
    " ",
    "删除指定的别名。注意双引号是必需的。 ",
    "--all 将移除你设置的所有别名。",
    " ",
    "举个例子，如果一个别名是这样声明的：",
    " ",
    '    alias r="run"',
    " ",
    "那么可以这样移除它：",
    " ",
    "    unalias r",
    " ",
    "使用 'unalias' 时无需区分全局别名和非全局别名",
    " ",
  ],
  vim: TemplatedHelpTexts.scriptEditor("vim"),
  weaken: [
    "用法：weaken",
    " ",
    "降低当前服务器的安全等级。缩短在此服务器上进行所有操作所需的时间。",
    "需要 root 权限。",
    "更多信息请前往 文档 > 资源 > NS API 文档 > Weaken。",
    " ",
  ],
  wget: [
    "用法：wget [url] [target file]",
    " ",
    "从 URL 检索数据并将其下载到当前服务器上的文件中。数据只能 ",
    "下载为脚本（.js、.jsx、.ts、.tsx）或文本文件（.txt、.json、.css）。",
    "如果文件已存在，将会被此命令覆盖。",
    " ",
    "注意，许多网站不允许跨源资源共享（CORS），因此无法从这些网站下载数据。示例：",
    " ",
    "    wget https://raw.githubusercontent.com/bitburner-official/bitburner-src/master/README.md game_readme.txt",
    " ",
  ],
};
