import ErrorStackParser from "error-stack-parser";
import { type RawSourceMap, SourceMapConsumer } from "source-map-js";

/**
 * parseStackTrace uses some properties of workerScript, but the dependency chain of WorkerScript is long. In order to
 * avoid worsening the dependency chain of parseStackTrace's callers, we create this minimal version of WorkerScript's
 * type. It violates the DRY principle, but it's worth the trouble:
 * - We rarely change WorkerScript.
 * - The entire codebase is riddled with massive dependency chains. We should avoid worsening the situation.
 */
export type LiteWorkerScript = {
  hostname: string;
  scriptRef: {
    dependencies: Map<
      unknown,
      {
        filename: string;
        mod: {
          sourceMap?: string;
        } | null;
      }
    >;
  };
};

/**
 * This function parses the stack trace of the error and returns only stack lines in the player's scripts. With
 * transformed scripts, it also parses the source map to show the original lines/columns of the original scripts.
 *
 * For example: This stack:
 *
 *   at errorMessage (webpack://bitburner/./src/Netscript/ErrorMessages.ts?:35:97)
 *   at Object.getServer (webpack://bitburner/./src/Netscript/NetscriptHelpers.tsx?:420:72)
 *   at eval (webpack://bitburner/./src/NetscriptFunctions.ts?:889:86)
 *   at Proxy.wrappedFunction (webpack://bitburner/./src/Netscript/APIWrapper.ts?:67:16)
 *   at test1 (home/a.ts:10:8)
 *   at main (home/a.ts:23:5)
 *   at startNetscript2Script (webpack://bitburner/./src/NetscriptWorker.ts?:91:9)
 *
 * Becomes:
 *
 *   at test1 (home/a.ts:11:5)
 *   at main (home/a.ts:26:2)
 *
 * There are 2 changes:
 * - All stack lines pointing to our codebase are stripped.
 * - Stack lines show original lines/columns (e.g., a.ts:23:5 -> home/a.ts:26:2).
 */
export function parseStackTrace(error: Error, workerScript: LiteWorkerScript): string {
  const stackFrames = ErrorStackParser.parse(error);
  const stackLines = [error.message];
  // Cache of found source maps.
  const sourceMaps = new Map<string, string>();
  for (const stackFrame of stackFrames) {
    if (!stackFrame.fileName) {
      continue;
    }
    /**
     * Filename in the stack line is actually `${hostname}/${filename}`. Check sourceURL in generateLoadedModule
     * (src\NetscriptJSEvaluator.ts).
     */
    if (!stackFrame.fileName.startsWith(workerScript.hostname)) {
      continue;
    }
    const fileName = stackFrame.fileName.replace(`${workerScript.hostname}/`, "");
    if (!fileName) {
      continue;
    }
    let line = stackFrame.lineNumber;
    let column = stackFrame.columnNumber;
    if (line !== undefined && column !== undefined) {
      let sourceMap = sourceMaps.get(fileName);
      // If the source map is not in the cache, we try to find it.
      if (!sourceMap) {
        /**
         * workerScript.scriptRef.dependencies contains directly or indirectly import, including the script itself.
         * Check Script in src\Script\Script.ts.
         */
        for (const script of workerScript.scriptRef.dependencies.values()) {
          // Find the current script in workerScript.scriptRef.dependencies.
          if (script.filename !== fileName) {
            continue;
          }
          // Check if sourceMap exists.
          if (script.mod?.sourceMap) {
            sourceMap = script.mod.sourceMap;
            // Put it in the cache.
            sourceMaps.set(fileName, sourceMap);
          }
          break;
        }
      }
      // Parse the source map if it exists.
      if (sourceMap) {
        /**
         * SourceMap is generated by SWC, so we assume that it's valid. Validating it with ajv is unnecessary. If there
         * are bugs in SWC or source-map-js, the try-catch block will ensure that the game won't crash.
         */
        try {
          const sourceMapConsumer = new SourceMapConsumer(JSON.parse(sourceMap) as RawSourceMap);
          ({ line, column } = sourceMapConsumer.originalPositionFor({ line, column }));
        } catch (errorParsingSourceMap) {
          console.error(errorParsingSourceMap);
          console.error(`Cannot parse map of ${fileName} in ${workerScript.hostname}. Source map: ${sourceMap}`);
        }
      }
    }
    stackLines.push(`    at ${stackFrame.functionName} (${workerScript.hostname}/${fileName}:${line}:${column})`);
  }
  return stackLines.join("\n");
}
