// This file contains almost all features that markdown ever uses. It is split by section to be better able to test different features.
// This file isn't used at the moment but should be included when we verify that Markdown is rendered correctly.

const headers =
  "# Headers\r\n\r\n```\r\n# h1 Heading 8-)\r\n## h2 Heading\r\n### h3 Heading\r\n#### h4 Heading\r\n##### h5 Heading\r\n###### h6 Heading\r\n\r\nAlternatively, for H1 and H2, an underline-ish style:\r\n\r\nAlt-H1\r\n======\r\n\r\nAlt-H2\r\n------\r\n```\t\r\n\r\n# h1 Heading 8-)\r\n## h2 Heading\r\n### h3 Heading\r\n#### h4 Heading\r\n##### h5 Heading\r\n###### h6 Heading\r\n\r\nAlternatively, for H1 and H2, an underline-ish style:\r\n\r\nAlt-H1\r\n======\r\n\r\nAlt-H2\r\n------\r\n\r\n------\r\n\r\n";
const emphasis =
  "# Emphasis\r\n\r\n```\r\nEmphasis, aka italics, with *asterisks* or _underscores_.\r\n\r\nStrong emphasis, aka bold, with **asterisks** or __underscores__.\r\n\r\nCombined emphasis with **asterisks and _underscores_**.\r\n\r\nStrikethrough uses two tildes. ~~Scratch this.~~\r\n\r\n**This is bold text**\r\n\r\n__This is bold text__\r\n\r\n*This is italic text*\r\n\r\n_This is italic text_\r\n\r\n~~Strikethrough~~\r\n```\r\n\r\nEmphasis, aka italics, with *asterisks* or _underscores_.\r\n\r\nStrong emphasis, aka bold, with **asterisks** or __underscores__.\r\n\r\nCombined emphasis with **asterisks and _underscores_**.\r\n\r\nStrikethrough uses two tildes. ~~Scratch this.~~\r\n\r\n**This is bold text**\r\n\r\n__This is bold text__\r\n\r\n*This is italic text*\r\n\r\n_This is italic text_\r\n\r\n~~Strikethrough~~\r\n\r\n------\r\n\r\n";

const lists =
  "# Lists\r\n\r\n```\r\n1. First ordered list item\r\n2. Another item\r\n\u22C5\u22C5* Unordered sub-list.\r\n1. Actual numbers don't matter, just that it's a number\r\n\u22C5\u22C51. Ordered sub-list\r\n4. And another item.\r\n\r\n\u22C5\u22C5\u22C5You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).\r\n\r\n\u22C5\u22C5\u22C5To have a line break without a paragraph, you will need to use two trailing spaces.\u22C5\u22C5\r\n\u22C5\u22C5\u22C5Note that this line is separate, but within the same paragraph.\u22C5\u22C5\r\n\u22C5\u22C5\u22C5(This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)\r\n\r\n* Unordered list can use asterisks\r\n- Or minuses\r\n+ Or pluses\r\n\r\n1. Make my changes\r\n    1. Fix bug\r\n    2. Improve formatting\r\n        - Make the headings bigger\r\n2. Push my commits to GitHub\r\n3. Open a pull request\r\n    * Describe my changes\r\n    * Mention all the members of my team\r\n        * Ask for feedback\r\n\r\n+ Create a list by starting a line with `+`, `-`, or `*`\r\n+ Sub-lists are made by indenting 2 spaces:\r\n  - Marker character change forces new list start:\r\n    * Ac tristique libero volutpat at\r\n    + Facilisis in pretium nisl aliquet\r\n    - Nulla volutpat aliquam velit\r\n+ Very easy!\r\n```\r\n\r\n1. First ordered list item\r\n2. Another item\r\n\u22C5\u22C5* Unordered sub-list.\r\n1. Actual numbers don't matter, just that it's a number\r\n\u22C5\u22C51. Ordered sub-list\r\n4. And another item.\r\n\r\n\u22C5\u22C5\u22C5You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).\r\n\r\n\u22C5\u22C5\u22C5To have a line break without a paragraph, you will need to use two trailing spaces.\u22C5\u22C5\r\n\u22C5\u22C5\u22C5Note that this line is separate, but within the same paragraph.\u22C5\u22C5\r\n\u22C5\u22C5\u22C5(This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)\r\n\r\n* Unordered list can use asterisks\r\n- Or minuses\r\n+ Or pluses\r\n\r\n1. Make my changes\r\n    1. Fix bug\r\n    2. Improve formatting\r\n        - Make the headings bigger\r\n2. Push my commits to GitHub\r\n3. Open a pull request\r\n    * Describe my changes\r\n    * Mention all the members of my team\r\n        * Ask for feedback\r\n\r\n+ Create a list by starting a line with `+`, `-`, or `*`\r\n+ Sub-lists are made by indenting 2 spaces:\r\n  - Marker character change forces new list start:\r\n    * Ac tristique libero volutpat at\r\n    + Facilisis in pretium nisl aliquet\r\n    - Nulla volutpat aliquam velit\r\n+ Very easy!\r\n\r\n------\r\n\r\n";

const taskLists =
  "# Task lists\r\n\r\n```\r\n- [x] Finish my changes\r\n- [ ] Push my commits to GitHub\r\n- [ ] Open a pull request\r\n- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported\r\n- [x] list syntax required (any unordered or ordered list supported)\r\n- [x] this is a complete item\r\n- [ ] this is an incomplete item\r\n```\r\n\r\n- [x] Finish my changes\r\n- [ ] Push my commits to GitHub\r\n- [ ] Open a pull request\r\n- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported\r\n- [x] list syntax required (any unordered or ordered list supported)\r\n- [ ] this is a complete item\r\n- [ ] this is an incomplete item\r\n\r\n------\r\n\r\n";

const ignoringMarkdownFormatting =
  "# Ignoring Markdown formatting\r\n\r\nYou can tell GitHub to ignore (or escape) Markdown formatting by using \\ before the Markdown character.\r\n\r\n```\r\nLet's rename \\*our-new-project\\* to \\*our-old-project\\*.\r\n```\r\n\r\nLet's rename \\*our-new-project\\* to \\*our-old-project\\*.\r\n\r\n------\r\n\r\n";
const links =
  "# Links\r\n\r\n```\r\n[I'm an inline-style link](https://www.google.com)\r\n\r\n[I'm an inline-style link with title](https://www.google.com \"Google's Homepage\")\r\n\r\n[I'm a reference-style link][Arbitrary case-insensitive reference text]\r\n\r\n[I'm a relative reference to a repository file](../blob/master/LICENSE)\r\n\r\n[You can use numbers for reference-style link definitions][1]\r\n\r\nOr leave it empty and use the [link text itself].\r\n\r\nURLs and URLs in angle brackets will automatically get turned into links.\r\nhttp://www.example.com or <http://www.example.com> and sometimes\r\nexample.com (but not on Github, for example).\r\n\r\nSome text to show that the reference links can follow later.\r\n\r\n[arbitrary case-insensitive reference text]: https://www.mozilla.org\r\n[1]: http://slashdot.org\r\n[link text itself]: http://www.reddit.com\r\n```\r\n\r\n[I'm an inline-style link](https://www.google.com)\r\n\r\n[I'm an inline-style link with title](https://www.google.com \"Google's Homepage\")\r\n\r\n[I'm a reference-style link][Arbitrary case-insensitive reference text]\r\n\r\n[I'm a relative reference to a repository file](../blob/master/LICENSE)\r\n\r\n[You can use numbers for reference-style link definitions][1]\r\n\r\nOr leave it empty and use the [link text itself].\r\n\r\nURLs and URLs in angle brackets will automatically get turned into links.\r\nhttp://www.example.com or <http://www.example.com> and sometimes\r\nexample.com (but not on Github, for example).\r\n\r\nSome text to show that the reference links can follow later.\r\n\r\n[arbitrary case-insensitive reference text]: https://www.mozilla.org\r\n[1]: http://slashdot.org\r\n[link text itself]: http://www.reddit.com\r\n\r\n------\r\n\r\n";

const images =
  '# Images\r\n\r\n```\r\nHere\'s our logo (hover to see the title text):\r\n\r\nInline-style:\r\n![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")\r\n\r\nReference-style:\r\n![alt text][logo]\r\n\r\n[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"\r\n\r\n![Minion](https://octodex.github.com/images/minion.png)\r\n![Stormtroopocat](https://octodex.github.com/images/stormtroopocat.jpg "The Stormtroopocat")\r\n\r\nLike links, Images also have a footnote style syntax\r\n\r\n![Alt text][id]\r\n\r\nWith a reference later in the document defining the URL location:\r\n\r\n[id]: https://octodex.github.com/images/dojocat.jpg  "The Dojocat"\r\n```\r\n\r\nHere\'s our logo (hover to see the title text):\r\n\r\nInline-style:\r\n![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")\r\n\r\nReference-style:\r\n![alt text][logo]\r\n\r\n[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"\r\n\r\n![Minion](https://octodex.github.com/images/minion.png)\r\n![Stormtroopocat](https://octodex.github.com/images/stormtroopocat.jpg "The Stormtroopocat")\r\n\r\nLike links, Images also have a footnote style syntax\r\n\r\n![Alt text][id]\r\n\r\nWith a reference later in the document defining the URL location:\r\n\r\n[id]: https://octodex.github.com/images/dojocat.jpg  "The Dojocat"\r\n\r\n------\r\n\r\n';
const footnotes =
  "# [Footnotes](https://github.com/markdown-it/markdown-it-footnote)\r\n\r\n```\r\nFootnote 1 link[^first].\r\n\r\nFootnote 2 link[^second].\r\n\r\nInline footnote^[Text of inline footnote] definition.\r\n\r\nDuplicated footnote reference[^second].\r\n\r\n[^first]: Footnote **can have markup**\r\n\r\n    and multiple paragraphs.\r\n\r\n[^second]: Footnote text.\r\n```\r\n\r\nFootnote 1 link[^first].\r\n\r\nFootnote 2 link[^second].\r\n\r\nInline footnote^[Text of inline footnote] definition.\r\n\r\nDuplicated footnote reference[^second].\r\n\r\n[^first]: Footnote **can have markup**\r\n\r\n    and multiple paragraphs.\r\n\r\n[^second]: Footnote text.\r\n\r\n------\r\n\r\n";

const codeAndSyntaxHighlighing =
  "# Code and Syntax Highlighting\r\n\r\n```\r\nInline `code` has `back-ticks around` it.\r\n```\r\n\r\nInline `code` has `back-ticks around` it.\r\n\r\n```javascript\r\nfunction $initHighlight(block, cls) {\r\n  try {\r\n    if (cls.search(/\\bno\\-highlight\\b/) != -1)\r\n      return process(block, true, 0x0F) +\r\n             ` class=\"${cls}\"`;\r\n  } catch (e) {\r\n    /* handle exception */\r\n  }\r\n  for (var i = 0 / 2; i < classes.length; i++) {\r\n    if (checkCondition(classes[i]) === undefined)\r\n      console.log('undefined');\r\n  }\r\n}\r\n\r\nexport  $initHighlight;\r\n```\r\n\r\n------\r\n\r\n";

const table =
  "# Tables\r\n\r\n```\r\nColons can be used to align columns.\r\n\r\n| Tables        | Are           | Cool  |\r\n| ------------- |:-------------:| -----:|\r\n| col 3 is      | right-aligned | $1600 |\r\n| col 2 is      | centered      |   $12 |\r\n| zebra stripes | are neat      |    $1 |\r\n\r\nThere must be at least 3 dashes separating each header cell.\r\nThe outer pipes (|) are optional, and you don't need to make the\r\nraw Markdown line up prettily. You can also use inline Markdown.\r\n\r\nMarkdown | Less | Pretty\r\n--- | --- | ---\r\n*Still* | `renders` | **nicely**\r\n1 | 2 | 3\r\n\r\n| First Header  | Second Header |\r\n| ------------- | ------------- |\r\n| Content Cell  | Content Cell  |\r\n| Content Cell  | Content Cell  |\r\n\r\n| Command | Description |\r\n| --- | --- |\r\n| git status | List all new or modified files |\r\n| git diff | Show file differences that haven't been staged |\r\n\r\n| Command | Description |\r\n| --- | --- |\r\n| `git status` | List all *new or modified* files |\r\n| `git diff` | Show file differences that **haven't been** staged |\r\n\r\n| Left-aligned | Center-aligned | Right-aligned |\r\n| :---         |     :---:      |          ---: |\r\n| git status   | git status     | git status    |\r\n| git diff     | git diff       | git diff      |\r\n\r\n| Name     | Character |\r\n| ---      | ---       |\r\n| Backtick | `         |\r\n| Pipe     | \\|        |\r\n```\r\n\r\nColons can be used to align columns.\r\n\r\n| Tables        | Are           | Cool  |\r\n| ------------- |:-------------:| -----:|\r\n| col 3 is      | right-aligned | $1600 |\r\n| col 2 is      | centered      |   $12 |\r\n| zebra stripes | are neat      |    $1 |\r\n\r\nThere must be at least 3 dashes separating each header cell.\r\nThe outer pipes (|) are optional, and you don't need to make the\r\nraw Markdown line up prettily. You can also use inline Markdown.\r\n\r\nMarkdown | Less | Pretty\r\n--- | --- | ---\r\n*Still* | `renders` | **nicely**\r\n1 | 2 | 3\r\n\r\n| First Header  | Second Header |\r\n| ------------- | ------------- |\r\n| Content Cell  | Content Cell  |\r\n| Content Cell  | Content Cell  |\r\n\r\n| Command | Description |\r\n| --- | --- |\r\n| git status | List all new or modified files |\r\n| git diff | Show file differences that haven't been staged |\r\n\r\n| Command | Description |\r\n| --- | --- |\r\n| `git status` | List all *new or modified* files |\r\n| `git diff` | Show file differences that **haven't been** staged |\r\n\r\n| Left-aligned | Center-aligned | Right-aligned |\r\n| :---         |     :---:      |          ---: |\r\n| git status   | git status     | git status    |\r\n| git diff     | git diff       | git diff      |\r\n\r\n| Name     | Character |\r\n| ---      | ---       |\r\n| Backtick | `         |\r\n| Pipe     | \\|        |\r\n\r\n------\r\n\r\n";

const Blockquotes =
  "# Blockquotes\r\n\r\n```\r\n> Blockquotes are very handy in email to emulate reply text.\r\n> This line is part of the same quote.\r\n\r\nQuote break.\r\n\r\n> This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can *put* **Markdown** into a blockquote.\r\n\r\n> Blockquotes can also be nested...\r\n>> ...by using additional greater-than signs right next to each other...\r\n> > > ...or with spaces between arrows.\r\n```\r\n\r\n> Blockquotes are very handy in email to emulate reply text.\r\n> This line is part of the same quote.\r\n\r\nQuote break.\r\n\r\n> This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can *put* **Markdown** into a blockquote.\r\n\r\n> Blockquotes can also be nested...\r\n>> ...by using additional greater-than signs right next to each other...\r\n> > > ...or with spaces between arrows.\r\n\r\n------\r\n\r\n";

const inlineHTML =
  "# Inline HTML\r\n\r\n```\r\n<dl>\r\n  <dt>Definition list</dt>\r\n  <dd>Is something people use sometimes.</dd>\r\n\r\n  <dt>Markdown in HTML</dt>\r\n  <dd>Does *not* work **very** well. Use HTML <em>tags</em>.</dd>\r\n</dl>\r\n```\r\n\r\n<dl>\r\n  <dt>Definition list</dt>\r\n  <dd>Is something people use sometimes.</dd>\r\n\r\n  <dt>Markdown in HTML</dt>\r\n  <dd>Does *not* work **very** well. Use HTML <em>tags</em>.</dd>\r\n</dl>\r\n\r\n------\r\n\r\n";

const horizontalRules =
  "# Horizontal Rules\r\n\r\n```\r\nThree or more...\r\n\r\n---\r\n\r\nHyphens\r\n\r\n***\r\n\r\nAsterisks\r\n\r\n___\r\n\r\nUnderscores\r\n```\r\n\r\nThree or more...\r\n\r\n---\r\n\r\nHyphens\r\n\r\n***\r\n\r\nAsterisks\r\n\r\n___\r\n\r\nUnderscores\r\n\r\n------\r\n\r\n";

const YoutubeVideos =
  '# YouTube Videos\r\n\r\n```\r\n<a href="http://www.youtube.com/watch?feature=player_embedded&v=YOUTUBE_VIDEO_ID_HERE" target="_blank">\r\n<img src="http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg" alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10">\r\n</a>\r\n```\r\n\r\n<a href="http://www.youtube.com/watch?feature=player_embedded&v=YOUTUBE_VIDEO_ID_HERE" target="_blank">\r\n<img src="http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg" alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10">\r\n</a>\r\n\r\n```\r\n[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)\r\n```\r\n\r\n[![IMAGE ALT TEXT HERE](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/YouTube_logo_2015.svg/1200px-YouTube_logo_2015.svg.png)](https://www.youtube.com/watch?v=ciawICBvQoE)';

const all =
  headers +
  emphasis +
  lists +
  taskLists +
  ignoringMarkdownFormatting +
  links +
  images +
  footnotes +
  codeAndSyntaxHighlighing +
  table +
  Blockquotes +
  inlineHTML +
  horizontalRules +
  YoutubeVideos;

export const markdownSample = all;
