name: "Deploy to GH Pages"

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node environment
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Build
      - run: npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "."
      - name: Deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v1
